version: "3.8"

services:
  superlists:
    build:
      context: .
      args:
        buildno: 1
    container_name: superlistsapp
    ports:
      - "8003:8000"
    volumes:
      - ./:/var/www
#      - /var/www/static/:/var/www/static/
#    networks:
#      - superlists
#
#  lists-server:
#    container_name: lserver
#    image: nginx:latest
#    depends_on:
#      - superlists
#    ports:
#      - "8098:8000"
#      - "448:443"
#    volumes:
#      - ./:/var/www
#      - /var/www/static/:/var/www/static/
#      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
#    networks:
#      - superlists
#
#networks:
#  superlists:
#    name: superlists
